import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        URL: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        ReadableStream: 'readonly',
        CompressionStream: 'readonly',
        Response: 'readonly',
        crypto: 'readonly',
        structuredClone: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        MutationObserver: 'readonly',
        IntersectionObserver: 'readonly',
        CustomEvent: 'readonly',
        performance: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        self: 'readonly',
        global: 'readonly',
        logger: 'readonly',
        Notyf: 'readonly',
        ProgressBar: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'prefer-const': 'warn',
      eqeqeq: ['error', 'smart'],
      'no-control-regex': 'off',
      'no-useless-assignment': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  {
    files: ['Parsed/parser/module*.{js,mjs,cjs}'],
    rules: {
      'no-unused-vars': 'off',
      'prefer-const': 'off',
    },
  },
  {
    files: ['**/*.cjs'],
    languageOptions: {
      globals: {
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
      },
    },
  },
  {
    ignores: [
      'frontend/dist/**',
      'Parsed/parser/model/secure.js',
      'Parsed/upload/**',
      'Parsed/.output/**',
      'logs/**',
      'site/dev/js/pdf.worker.mjs',
      'site/dev/js/pdf.mjs',
      'site/dev/js/progressbar.js',
      'site/dev/js/notyf.js',
      'ENGINE/Part/Engine/_knowledge/mainrules.js',
      'ENGINE/Part/Engine/_knowledge/template.js',
      'jsconfig.js',
    ],
  },
  prettier,
];